name: Autograding Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    # Evita que el bot de Classroom dispare recursivamente
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run tests
        run: make